from .models import MindPalace, Room

# Mind palace to practice the major system
# each object represents one of the 100 pair of possible digits
# e.g 00 = Zeus, 01 = seed

mind_palace = MindPalace(
    name="Cloud Needle Isle",
    rooms=[
        Room(
            room_name="Welcoming Pier",
            objects=[
                "seed",
                "sun",
                "sumo",
                "sir",
                "soul",
                "sushi",
                "ski",
                "sofa",
                "soap",
                "dice",
            ],
        ),
        Room(
            room_name="Hall of the Ancestors",
            objects=[
                "dad",
                "DNA",
                "Adam",
                "Thor",
                "tail",
                "DJ",
                "dog",
                "TV",
                "tuba",
                "nose",
            ],
        ),
        Room(
            room_name="Wharf of the Nets",
            objects=[
                "net",
                "nun",
                "Nemo",
                "winner",
                "nail",
                "nacho",
                "ink",
                "knife",
                "NBA",
                "mouse",
            ],
        ),
        Room(
            room_name="Moon Arcade",
            objects=[
                "mat",
                "moon",
                "mummy",
                "Mario",
                "mule",
                "mochi",
                "Mickey",
                "mafia",
                "map",
                "rose",
            ],
        ),
        Room(
            room_name="Storm Roof",
            objects=[
                "radio",
                "rana",
                "arm",
                "error",
                "Ariel",
                "arch",
                "rocky",
                "roof",
                "harp",
                "lasso",
            ],
        ),
        Room(
            room_name="Boiling Lagoon",
            objects=[
                "lady",
                "lion",
                "llama",
                "lawyer",
                "lolly",
                "leech",
                "lock",
                "lava",
                "lip",
                "cheese",
            ],
        ),
        Room(
            room_name="Bubbling Kitchen",
            objects=[
                "cheetah",
                "genie",
                "jam",
                "cherry",
                "chili",
                "yo yo",
                "check",
                "chef",
                "chip",
                "goose",
            ],
        ),
        Room(
            room_name="Getaway Garage",
            objects=[
                "cat",
                "gun",
                "gum",
                "car",
                "koala",
                "cage",
                "cake",
                "coffee",
                "cube",
                "face",
            ],
        ),
        Room(
            room_name="Foam Beach",
            objects=[
                "food",
                "fan",
                "foam",
                "fire",
                "fly",
                "fish",
                "foca",
                "FIFA",
                "Phoebe",
                "bass",
            ],
        ),
        Room(
            room_name="Cloud Needle",
            objects=[
                "bat",
                "piano",
                "beam",
                "bear",
                "apple",
                "bush",
                "pig",
                "beef",
                "baby",
                "Zeus",
            ],
        ),
    ],
)
