from .models import MindPalace, Room

mind_palace = MindPalace(
    name="Medieval Palace",
    rooms=[
        Room(
            room_name="Armory",
            objects=[
                "knight armor",
                "open chest",
                "bow rack",
                "hand weapons",
                "shields"
            ],
        ),
        Room(
            room_name="Food Storage",
            objects=[
                "water vases",
                "grain sacks",
                "food shelf",
                "ham leg",
                "cheese",
                "sausages",
                "crates",
                "bread basket",
                "corked bottle",
                "barrel rack"
            ],
        ),
        Room(
            room_name="Snack Room",
            objects=[
                "cabinet",
                "small candelabrum",
                "round table",
                "grapes",
                "wine jar",
                "floor candelabrum",
                "snacking bench",
                "dining table",
                "jumping bread buns",
                "beer mugs"
            ],
        ),
        Room(
            room_name="Bar",
            objects=[
                "broom",
                "bar counter",
                "shield and sword",
                "fish plate",
                "salt",
                "bar stools",
                "rum keg",
                "note stand",
                "piano",
                "piano stool"
            ],
        ),
        Room(
            room_name="Servants Quarters",
            objects=[
                "bathtub",
                "sponge",
                "wooden screen",
                "scheduled whiteboard",
                "servants bed",
                "table",
                "pitcher",
                "cups",
                "candle",
                "bread",
                "stool",
                "hammock",
                "clothesline",
                "bench",
                "bucket"
            ],
        ),
        Room(
            room_name="Kitchen",
            objects=[
                "food table",
                "cabbage basket",
                "apples and corn",
                "fire poker",
                "stone oven",
                "receipt book stand",
                "apple pie",
                "cooking island",
                "cutting board",
                "pot of soup",
                "tea kettle",
                "soup spoon",
                "chair",
                "kitchen table",
                "oatmeal"
            ],
        ),
        Room(
            room_name="Dining Hall",
            objects=[
                "brewing rack",
                "towel rack",
                "pig roast",
                "wall map",
                "dinner table",
                "plates",
                "black pepper",
                "turkey",
                "cups with water",
                "red apples",
                "dining bench",
                "fireplace",
                "excalibur sword",
                "firewood",
                "wood pliers"
            ],
        ),
        Room(
            room_name="Workshop",
            objects=[
                "wagon wheel",
                "soccer top",
                "brush",
                "wagon table",
                "saddle seat",
                "lantern",
                "inner wheel",
                "leather belts",
                "horse statue",
                "faun painting",
                "work stool",
                "work bench",
                "horseshoes",
                "rope",
                "horse figure",
                "pliers",
                "hammer",
                "anvil",
                "leather mat",
                "utility box"
            ],
        ),
        Room(
            room_name="Reading Lounge",
            objects=[
                "bookshelf with drawers",
                "reading table",
                "eyeglasses",
                "scrolls",
                "wooden sofa"
            ],
        ),
        Room(
            room_name="Training Room",
            objects=[
                "axe",
                "whetstone",
                "training dummy",
                "targets",
                "javelin",
                "emblem flag",
                "ball and chain",
                "arrows",
                "crossbow",
                "foil"
            ],
        ),
        Room(
            room_name="Single Bedroom",
            objects=[
                "bedside dresser",
                "red rose",
                "decorated jar",
                "wall sword",
                "single bed",
                "private chest",
                "floor candle stand",
                "closet",
                "boots",
                "shield"
            ],
        ),
        Room(
            room_name="Children's Room",
            objects=[
                "children's wardrobe",
                "pet plant",
                "puppet theater",
                "art stool",
                "easel with painting",
                "bunk bed",
                "doll",
                "lute",
                "cozy chair",
                "rocking horse"
            ],
        ),
        Room(
            room_name="Couple's Bedroom",
            objects=[
                "water bowl",
                "jade plant",
                "master bed",
                "open book",
                "toy cat",
                "knitting basket",
                "makeup stool",
                "makeup table",
                "jewelry box",
                "perfume",
                "hairbrush",
                "round bedroom table",
                "envelope",
                "hand fan",
                "dress"
            ],
        ),
        Room(
            room_name="Treasury",
            objects=[
                "horn",
                "dragon harp",
                "epic sword",
                "book podium",
                "sacred book",
                "golden candelabrum",
                "golden shield",
                "golden coins",
                "treasure chest",
                "tall gold pitcher",
                "glass display",
                "king's amulet",
                "king's helmet",
                "king's crown",
                "gem bag"
            ],
        ),
        Room(
            room_name="Library",
            objects=[
                "big bookshelf",
                "small bookshelf",
                "bird cage",
                "spyglass",
                "letter chest",
                "pendulum clock",
                "writing desk",
                "magnifying glass",
                "letter",
                "feather pen",
                "terrestrial globe",
                "cushion chair",
                "islands map",
                "narrow bookshelf",
                "ladder"
            ],
        ),
        Room(
            room_name="Laboratory",
            objects=[
                "flytrap plant",
                "bookcase stand",
                "small melting pot",
                "scales",
                "vase with spoons",
                "potion cauldron",
                "potion cupboard",
                "green potion bottles",
                "crystal table",
                "violet crystals",
                "wizard's table",
                "magical candles",
                "crystal ball",
                "wooden mortar",
                "small stool",
                "distillery cabinet",
                "distiller system",
                "safety goggles",
                "acid",
                "book of magic"
            ],
        )
    ],
)
